import { notesAPI, quizAPI, tutorAPI } from './api';
import { Question, QuizLevel, QuestionType, SmartNotes, AIResponseData } from '../types';

// --- Core Functions ---

export const generateSummary = async (content: string, type: 'text' | 'image' | 'pdf' | 'audio'): Promise<string> => {
  // Deprecated: Summary is generated by backend during upload.
  return "Summary generation is handled by the server.";
};

export const processDocument = async (content: string): Promise<AIResponseData> => {
  throw new Error("processDocument is deprecated. Use backend generation.");
};

export const generateSmartNotes = async (materialId: string): Promise<SmartNotes> => {
  const response = await notesAPI.generate(materialId);
  // Assuming backend returns { ...metadata, notes_data: SmartNotes } or similar.
  // Based on notes.py, it returns SmartNotesResponse which has notes_data.
  return response.notes_data;
};

export const askTutor = async (history: { role: 'user' | 'model', text: string }[], newQuestion: string, materialId?: string): Promise<string> => {
  try {
    const response = await tutorAPI.chat({
      messages: history,
      material_id: materialId
    });
    return response.response;
  } catch (error) {
    console.error("Chat Error:", error);
    return "Sorry, I encountered an error answering that.";
  }
};

export const generateAdvancedQuestions = async (
  materialId: string,
  level: QuizLevel,
  type: QuestionType,
  count: number
): Promise<Question[]> => {
  try {
    const response = await quizAPI.generate({
      material_id: materialId,
      difficulty: level,
      question_type: type,
      count: count
    });
    return response.questions || [];
  } catch (error) {
    console.error("Advanced Quiz generation error:", error);
    throw new Error("Failed to generate quiz.");
  }
};

export const generateQuiz = async (materialId: string, level: QuizLevel): Promise<Question[]> => {
  return generateAdvancedQuestions(materialId, level, 'multiple-choice', 5);
};

export const askStrictTutor = async (history: { role: 'user' | 'model', text: string }[], newQuestion: string, materialId?: string): Promise<string> => {
  // Using standard chat for now as strict mode isn't explicitly exposed in api.ts yet
  return askTutor(history, newQuestion, materialId);
};

export const evaluateAnswer = async (
  question: string,
  userAnswer: string,
  modelAnswer: string,
  maxMarks: number
): Promise<{ score: number; feedback: string }> => {
  try {
    const response = await tutorAPI.evaluate({
      question,
      user_answer: userAnswer,
      model_answer: modelAnswer,
      max_marks: maxMarks
    });
    return response;
  } catch (error) {
    console.error("Evaluation Error:", error);
    return { score: 0, feedback: "Failed to evaluate answer." };
  }
};
