from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
import io
from typing import Dict, Any

def create_docx_from_notes(notes: Dict[str, Any], title: str) -> io.BytesIO:
    """
    Create a styled DOCX file from smart notes
    
    Args:
        notes: Smart notes data dictionary
        title: Document title
        
    Returns:
        BytesIO object containing the DOCX file
    """
    doc = Document()
    
    # Title
    heading = doc.add_heading(title, 0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Summary Section
    doc.add_heading('Summary', level=1)
    summary_para = doc.add_paragraph(notes.get('summary', ''))
    summary_para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    
    # Key Concepts (Bullet Points)
    if notes.get('bulletPoints'):
        doc.add_heading('Key Concepts', level=1)
        for point in notes['bulletPoints']:
            doc.add_paragraph(point, style='List Bullet')
            
    # Detailed Notes
    if notes.get('detailedNotes'):
        doc.add_heading('Detailed Notes', level=1)
        for section in notes['detailedNotes']:
            # Handle both string and object formats
            if isinstance(section, dict):
                heading_text = section.get('heading', '')
                content_text = section.get('content', '')
                if heading_text:
                    doc.add_heading(heading_text, level=2)
                if content_text:
                    doc.add_paragraph(content_text)
            else:
                doc.add_paragraph(str(section))

    # Definitions
    if notes.get('definitions'):
        doc.add_heading('Key Definitions', level=1)
        table = doc.add_table(rows=1, cols=2)
        table.style = 'Table Grid'
        
        # Header
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Term'
        hdr_cells[1].text = 'Definition'
        
        # Make header bold
        for cell in hdr_cells:
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.bold = True
        
        # Rows
        for definition in notes['definitions']:
            row_cells = table.add_row().cells
            row_cells[0].text = definition.get('term', '')
            row_cells[1].text = definition.get('definition', '')
            
    # Mind Map (Text representation)
    if notes.get('mindMap'):
        doc.add_heading('Topic Structure', level=1)
        for topic in notes['mindMap']:
            p = doc.add_paragraph()
            run = p.add_run(topic.get('topic', ''))
            run.font.bold = True
            
            for subtopic in topic.get('subtopics', []):
                doc.add_paragraph(subtopic, style='List Bullet 2')

    # Footer
    section = doc.sections[0]
    footer = section.footer
    paragraph = footer.paragraphs[0]
    paragraph.text = "Generated by StudentAI"
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Save to memory
    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    
    return file_stream
